### ISSUE TITLE
Foldable t a

### ISSUE THREAD

**Issue by imcodlaw** [Zenius2016/BoardAlfa#10]
```
:t length 
length :: [a] -> Int
(mac version)
```

```
:t length
Foldable t => t a -> Int
(windows version)

```

I just found this confusing situation when I watched the tutorial video posted in Youtube. If I were a newbie, (actually I am) i will never solve any kind of problem that involve this function. I critically need explanation, because I think this kind of problem may cause misunderstanding. I thought that "Foldable" type is unprime number, because it can be "folded" (divided) by another number for example. Need explanation from experts. Thanks. 

```
```

**Comment by squest** [comment]
It's not a difference between mac and windows, some mac displays [x] some other mac displays Foldable t => t a.

So, for now just think Foldable t => t a  the same as [a].

**Comment by Nangakalashnikov** [comment]
I haven't been understanding the Foldable t => t a the same as [a] .
Could you give me the details please ?

**Comment by skadinyo** [comment]
For example,
If you want to see the type of length, you expect to get this

```
:t length 
length :: [a] -> Int
```

but, turns out you get

```
:t length
Foldable t => t a -> Int
```

just read `t a` as `[a]`
