### ISSUE TITLE
Win 10

### ISSUE THREAD

**Issue by lyviac** [Zenius2016/BoardAlfa#11]
is Github also available in Windows 10 too?

**Comment by skadinyo** [comment]
There is an installer for windows 7 or later here: (https://desktop.github.com), but i haven't tested it in windows 10. It might work, if not then you can use github from your browser. 
![github](https://cloud.githubusercontent.com/assets/10598231/9830487/6aba7b92-595a-11e5-8d99-fb44647f4f77.png)

**Comment by skadinyo** [comment]
@lyviac It seems you have attempt to do the first assignment, so i assume you have installed github. I close this issue then.
