### ISSUE TITLE
Can't install github for windows 8

### ISSUE THREAD

**Issue by aldinosyaputra** [Zenius2016/BoardAlfa#4]
i've been trying any solutions from net, but the result still nil. http://stackoverflow.com/questions/25439865/unable-to-install-github-for-windows. I got solutions there, but nothing worked for me.

**Comment by skadinyo** [comment]
do you use windows 8 or 8.1 ? If you use 8, change to 8.1. because the solution in stackoverflow is for 8.1.

**Comment by skadinyo** [comment]
If you can't install github desktop then use github browser. i'll close this issue then.
