### ISSUE TITLE
can't install github for windows 7, ide haskell, and language haskell.

### ISSUE THREAD

**Issue by putrim** [Zenius2016/BoardAlfa#5]
![untitled](https://cloud.githubusercontent.com/assets/13994326/9622760/c675b09c-5161-11e5-8638-df471842d44b.jpg)

![github](https://cloud.githubusercontent.com/assets/13994326/9622762/d05ba512-5161-11e5-9857-e1fb581e825f.jpg)

![github details](https://cloud.githubusercontent.com/assets/13994326/9622779/f9c9f714-5161-11e5-9694-b11ed3796ff2.jpg)

**Comment by skadinyo** [comment]
For now,

Github Desktop alternative
use Github browser to change things in your repo

Atom alternative is heat.
