### ISSUE TITLE
Can't install Atom.io in Windows 8.1

### ISSUE THREAD

**Issue by tunggadewi** [Zenius2016/BoardAlfa#8]
When I tried to install it on my WIndows 8.1, I got this error.

![](http://i.imgur.com/nVPa5kw.png)

I've deleted it and re-downloaded it again, but nope, the issue is still exist.
Help?!

**Comment by tunggadewi** [comment]
Alright, I think I must have been using Heat instead. :smiley_cat:

**Comment by skadinyo** [comment]
Okay then, i will close this issue
